name: Frontend Build and Test Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  frontend-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install

    - name: Set environment variables
      run: |
        echo "REACT_APP_BACKEND_URL=https://park-hopper-backend-8a49b628e08c.herokuapp.com/api" >> .env

    # - name: Build the frontend
    #   run: |
    #     npm run build

    # - name: Test the frontend
    #   run: |
    #     npm test -- --watchAll=false

    # - name: Deploy frontend (dry run)
    #   run: |
    #     npm run predeploy
